spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.250.211.87:3307/gulimall_sms
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 10.250.211.87
    port: 6379
  #服务追踪
  zipkin:
    base-url: http://10.250.211.87:9411