spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.250.211.87:3307/gulimall_oms
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  #服务追踪
  zipkin:
    base-url: http://192.168.1.107:9411