spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8833
        port: 8719
    alicloud:
      access-key: LTAI4tFnRMJQVvfsyXaurNmo
      secret-key: eKtByXS0L5lWiXrqLCzSbLfzgTBJlD
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: lxtkj
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        method: POST
        appcode: 0f23453297fc4bb592a84bf14bf8de3c

  application:
    name: gulimall-third-party
server:
  port: 30000

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'