spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8833
        port: 8719
  application:
    name: gulimall-cart
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面
  session:
    store-type: redis
  #服务追踪
  zipkin:
    discovery-client-enabled: false
    sender:
      type: web
  #配置采样器
  sleuth:
    sampler:
      probability: 1

server:
  port: 8140

  servlet:
    session:
      timeout: 30m

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    cn.lxtkj.gulimall.auth.feign.ThirdPartFeignService: debug
